---
- name: download kind release
  get_url:
    url: "{{ kind_release_path }}"
    dest: /home/{{ ansible_user_id }}/kind

- name: move kind to bin path
  become: true
  command: mv /home/{{ ansible_user_id }}/kind /usr/local/bin

- name: set kind executable owner
  become: true
  file:
    path: /usr/local/bin/kind
    owner: root
    group: root
    mode: 0555
