---
- name: install golang package
  become: true
  unarchive:
    remote_src: true
    src: "{{ golang_release_path }}"
    dest: "{{ extract_path }}"

- name: make sure gopath exists
  file:
    path: "{{ gopath }}"
    state: directory
    mode: 0644

- name: add GOPATH in bashrc
  lineinfile:
    path: /home/{{ ansible_user_id }}/.bashrc
    line: export GOPATH={{ gopath }}
    insertafter: EOF
    state: present

- name: add go/bin path in profile
  become: true
  lineinfile:
    path: /etc/profile
    line: export PATH=$PATH:/usr/local/go/bin
    insertafter: EOF
    state: present