- name: download helm release
  get_url:
    url: https://get.helm.sh/helm-v3.2.0-rc.1-linux-amd64.tar.gz
    dest: /home/{{ ansible_user_id }}/
    mode: 0666
  register: out

- name: unarchive helm
  become: true
  unarchive:
    remote_src: true
    src: "{{ out.dest }}"
    dest: /home/{{ ansible_user_id }}
    list_files: true
  register: archive_contents

- name: copy helm to local temp folder
  become: true
  copy:
    src: /home/{{ ansible_user_id }}/{{ archive_contents.files[0].split('/')[0] }}/helm
    dest: "/usr/local/bin/helm"
    remote_src: true
    owner: root
    group: root
    mode: 0555

- name: remove files
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ out.dest }}"
    - /home/{{ ansible_user_id }}/{{ archive_contents.files[0].split('/')[0] }}
  