---
- hosts: home_server
#- hosts: localhost
#  connection: local
  roles:
    - role: "../roles/virtualbox"
      tags: virtualbox
    - role: "../roles/vagrant"
      tags: vagrant
    - role: "../roles/docker"
      tags: docker
    - role: "../roles/python"
      tags: python
    - role: "../roles/golang"
      tags: golang
    - role: "../roles/nodejs"
      tags: nodejs
    - role: "../roles/code_server"
      tags: code
    - role: "../roles/kind"
      tags: kind
    - role: "../roles/kubectl"
      tags: kubectl
    - role: "../roles/helm"
      tags: helm

