---
- name: check temporary vagrant folder exist
  stat: 
    path: "{{ vagrant_tmpdir }}/Vagrantfile"
  register: stat_result

- name: destroy existing vagrant machine
  shell: "cd {{ vagrant_tmpdir }}; vagrant destroy -f; cd -"
  when: stat_result.stat.exists
  register: out

- debug: var=out.stdout_lines

- name: create temporary vagrant folder
  file:
    path: "{{ vagrant_tmpdir }}"
    state: directory
  when: not stat_result.stat.exists  

- name: copy vagrant file
  template:
    src: Vagrantfile.j2
    dest: "{{ vagrant_tmpdir }}/Vagrantfile"

- name: vagrant up
  shell: "cd {{ vagrant_tmpdir }}; vagrant up; cd -"
  register: out

- debug: var=out.stdout_lines