- name: get latest stable release version
  uri: 
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: true
  register: ver

- name: get latest kubectl
  become: true
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ ver.content | trim }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl

- name: change mode and permission
  become: true
  file:
    path: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0555
