- name: add virtual box apt-key
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - https://www.virtualbox.org/download/oracle_vbox.asc

- name: check virtual box apt key has not been altered
  become: yes
  command: apt-key fingerprint {{ item.tail }}
  register: fingerprint_check
  changed_when: False
  failed_when: "'{{ item.key }}' not in fingerprint_check.stdout"
  with_items:
    - { key: "B9F8 D658 297A F3EF C18D  5CDF A2F6 83C5 2980 AECF", tail: "2980AECF" }
    - { key: "7B0F AB3A 13B9 0743 5925  D9C9 5442 2A4B 98AB 5139", tail: "98AB5139" }

- name: add virtual box apt repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    state: present

- name: install virtual box
  become: true
  apt:
    name: virtualbox-6.1
    update_cache: true
