---
- name: install prerequisite packages
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: true

- name: add docker apt-key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: check Docker apt key has not been altered
  become: yes
  command: apt-key fingerprint 0EBFCD88
  register: fingerprint_check
  changed_when: False
  failed_when: "'9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88' not in fingerprint_check.stdout"

- name: add docker apt repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present

- name: install docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

- name: add user to docker group
  become: true
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true

- name: install docker compose
  become: true 
  shell: |-
    curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: let docker compose executable
  become: true  
  file:
    path: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0555
  